import "./globals.css";

export const metadata = {
  title: "Walentynka",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gradient-to-b from-pink-100 to-pink-300 p-5">
        {children}
      </body>
    </html>
  );
}
